export {Teams} from './Teams'
export {Home} from './Home'
export {TeamInfo} from './TeamInfo'
export {Register} from './Register'
export {Dashboard} from './Dashboard'
export {Login} from './Login'
export {NewPerson} from './NewPerson'
